import = [
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = false
opacity = 0.9
title = "Alacritty"

[window.padding]
x = 6
y = 6

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors]
transparent_background_colors = true
