import = [
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[window]
decorations = "none"
opacity = 0.95
title = "Alacritty"
dynamic_padding = false
blur = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 6

[font]
size = 11.5

