palette = "catppuccin_macchiato"
add_newline = true
format = "$directory$character"
right_format = "$all"

[directory]
read_only = " "
truncation_length = 10
truncation_symbol =  ".../"
truncate_to_repo = false
format = '[](fg:surface1)[$path](fg:text bg:surface1 bold)[█](fg:surface1)[](fg:blue bg:surface1)[ ](fg:mantle bg:blue italic)[](fg:blue) '

[git_status]
disabled = true

[package]
disabled = true

[git_branch]
symbol = " "
format =  "[$symbol$branch(:$remote_branch)]($style) "

[docker_context]
symbol = " "
format = "[$symbol($version)]($style) "

[gradle]
symbol = " " 
format = "[$symbol($version)]($style) "

[c]
symbol = " "
format = '[$symbol($version) (\($name\))]($style) '

[golang]
symbol = " "
format = "[$symbol($version)]($style) "

[java]
symbol = " "
format = "[$symbol($version)]($style) "

[lua]
symbol = " "
format = "[$symbol($version)]($style) "

[nodejs]
symbol = " "
format = "[$symbol($version)]($style) "

[python]
symbol = " "
format = '[$symbol($version) (\($virtualenv\))]($style) '

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
